
# get all users 
GET http://127.0.0.1:3000/626ea2676264e9fd516d7566

###
#get user by id 

GET http://127.0.0.1:3000/626ea2676264e9fd516d7566

###

#add user

POST http://127.0.0.1:3000/post
Content-Type: application/json

{
    "name":"yasin arfat",
    "email":"arfat@examole.com",
    "age":17
}

###
#Petch user / update user 

PATCH http://127.0.0.1:3000/626ea2676264e9fd516d7566
Content-Type: application/json

{
    "name":"arfat yasin",
    "email":"arfat@example.com",
    "age":18
   
}

#delete user by id 
###
DELETE http://127.0.0.1:3000/626ea83b23704755a131d808

